<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 29/06/2014 18:09:20
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->modelo_convite_id);

# Verificar se há um registro da imagem
$tem_imagem = $mod->modelo_convite_imagem != '';

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_MODELO_DE_CONVITE_VIRTUAL : TXT_TITULO_FORMULARIO_ALTERAR_MODELO_DE_CONVITE_VIRTUAL;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="modelo_convite" method="post" action="<?= \DL::$dir_raiz; ?>" enctype="multipart/form-data">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->modelo_convite_id; ?>" />
        <?php endif; ?>
        
        <label for="titulo"><?= TXT_LABEL_TITULO; ?>:</label><br />
        <input type="text" name="titulo" id="titulo" value="<?= $mod->modelo_convite_titulo; ?>" title="<?= TXT_LABEL_TITULO; ?>" />
        <br /><br />

        <!-- Inserir uma imagem para o modelo convite -->
        <div class="img-visual">
            <label for="imagem"><?= TXT_LABEL_IMAGEM; ?>:</label><br />
            <input type="file" name="imagem" id="imagem" title="<?= TXT_LABEL_IMAGEM; ?>" />

            <?php if( $tem_imagem ): ?>
            <br />
            <img src="<?= \DL::$dir_raiz; ?>/<?= $mod->modelo_convite_imagem; ?>" alt="" />
            <?php endif; ?>
        </div>
        
        <label><?= TXT_LABEL_PUBLICAR; ?></label>
        <input type="checkbox" name="publicar" id="publicar" value="1" class="s-ou-n"<?= $mod->modelo_convite_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
        <label for="publicar"></label>
        <br /><br/>
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='modelo_convite']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/convites-virtuais/modelos/lista";
            },
            <?php endif; ?>
            controle: "modeloconvite/salvar",
            campos  : {
                "titulo"    : { obr: true },
                <?php if( !$tem_imagem ): ?>
                "imagem"    : { obr: true },
                <?php endif; ?>
                "publicar"  : { obr: true, marcarobr: false, validacao: /^[0-1]{1}$/ }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    };
    //]]>
</script>