<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 06/08/2014 16:49:27
 */

$perm = $params['perm'];

?>

<div class="dl">
    <h1><?= TXT_TITULO_CONVITES_VIRTUAIS_ENVIADOS; ?></h1>
    
    <div class="mais-opcoes">        
        <?php include_once './visoes/painel-dl/_form_filtro.phtml'; ?>
    </div>
    
    <form name="editar-lista" method="post" action="<?= \DL::$dir_raiz; ?>">
        <table class="lista">
            <tr>
                <th id="id" class="td-id"><input type="checkbox" /></th>
                <th id="aniver"><?= TXT_TABELA_TITULO_ANIVERSARIANTE; ?></th>
                <th id="data"><?= TXT_TABELA_TITULO_DATA; ?></th>
                <th id="modelo"><?= TXT_TABELA_TITULO_MODELO; ?></th>
                <th id="opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
            </tr>
            
            <?php 
            if( !count($params['lista']) )
                echo '<tr><td colspan="5">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
            
            foreach( $params['lista'] as $l ): ?>
            <tr>
                <td headers="id" class="td-id">
                    <input type="checkbox" name="id[]" value="<?= $l['envio_convite_id']; ?>" />
                </td>
                <td headers="aniver"><?= $l['envio_convite_festa_aniversariante']; ?></td>
                <td headers="data"><?= \Funcoes::_formatardatahora($l['envio_convite_festa_data'], $_SESSION['formato_data_data']); ?></td>
                <td headers="modelo"><?= $l['modelo_convite_titulo']; ?></td>
                <td headers="opcoes" class="td-opcoes">
                    <a href="<?= \DL::$dir_raiz; ?>/painel-dl/convites-virtuais/envios/detalhes-do-envio/<?= $l['envio_convite_id']; ?>" class="lista editar">
                        <?= TXT_LINK_DETALHES; ?>
                    </a>
                    
                    <?php if( $perm['remover'] ): ?>
                    <a href="javascript:;" class="lista remover" title="<?= TXT_LINK_TITLE_REMOVER_REGISTRO; ?>" onclick="if( SelecionarLinha(this) ) RemoverRegistro('<?= MSG_PADRAO_DESEJA_REALMENTE_REMOVER_ESSE_REGISTRO; ?>');">
                        <?= TXT_LINK_REMOVER; ?>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            
            <tr class="com-marcados">
                <td colspan="5">
                    <?php if( $perm['remover'] ): ?>
                    <a href="javascript:;" class="remover" title="<?= TXT_LINK_TITLE_REMOVER_REGISTROS_SELECIONADOS; ?>" onclick="RemoverRegistro('<?= MSG_PADRAO_DESEJA_REALMENTE_REMOVER_REGISTROS_SELECIONADOS; ?>');">
                        <?= TXT_LINK_REMOVER; ?>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
        
        <div id="paginacao"></div>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        <?php if( $perm['remover'] ): ?>
        $editar_lista = $("form[name='editar-lista']")._dlformulario({
            controle    : "envioconvite/remover",
            depois      : function(){
                $(".lista :checkbox:checked").parents("tr").remove();
            },
            cktodos     : [true, "tr:first-child :checkbox:first-child", ":checkbox[name='id[]']"],
            aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        <?php endif; ?>
        
        $("#paginacao")._dlpaginacao({
            pgtotal     : <?= $params['qtde_pg']; ?>,
            mostrar     : 5,
            aparencia   : { tema: "<?= \FrameworkDL::$plugin_paginacao_tema; ?>", estilo: "paginacao" }
        });
    };
    //]]>
</script>