<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 18/06/2014 08:46:23
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->tipo_dado_id);

$tem_imagem = $mod->tipo_dado_icone != '';

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_TIPO_DE_DADO_PARA_CONTATO : TXT_TITULO_FORMULARIO_ALTERAR_TIPO_DE_DADO_PARA_CONTATO;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="tipo_dado" method="post" action="<?= \DL::$dir_raiz; ?>" enctype="multipart/form-data">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->tipo_dado_id; ?>" />
        <?php endif; ?>
        
        <label for="descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br />
        <input type="text" name="descr" id="descr" value="<?= $mod->tipo_dado_descr; ?>" title="<?= TXT_LABEL_DESCRICAO; ?>" />
        <br /><br />
        
        <!-- Inserir um ícone para o tipo de dado -->
        <div class="img-visual">
            <label for="imagem"><?= TXT_LABEL_ICONE; ?>:</label><br />
            <input type="file" name="imagem" id="imagem" title="<?= TXT_LABEL_ICONE; ?>" />

            <?php if( $tem_imagem ): ?>
            <br />
            <img src="<?= \DL::$dir_raiz; ?>/<?= $mod->tipo_dado_icone; ?>" alt="" />
            <?php endif; ?>
        </div>
        
        <label><?= TXT_LABEL_REDE_SOCIAL; ?></label>
        <input type="checkbox" name="rede_social" id="rede_social" value="1" class="s-ou-n"<?= $mod->tipo_dado_rede_social == 1 ? ' CHECKED' : ''; ?> />
        <label for="rede_social"></label>
        <br />
        
        <label><?= TXT_LABEL_PUBLICAR; ?></label>
        <input type="checkbox" name="publicar" id="publicar" value="1" class="s-ou-n"<?= $mod->tipo_dado_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
        <label for="publicar"></label>
        <br /><br />
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='tipo_dado']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/web-site/formas-de-contato/lista";
            },
            <?php endif; ?>
            controle: "tipodadocontato/salvar",
            campos  : {
                "descr"         : { obr: true },
                "rede_social"   : { obr: true, marcarobr: false, validacao: /^[0-1]$/ },
                "publicar"      : { obr: true, marcarobr: false, validacao: /^[0-1]$/ }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    };
    //]]>
</script>