<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 18/06/2014 08:46:23
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->dado_contato_id);

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_DADO_PARA_CONTATO : TXT_TITULO_FORMULARIO_ALTERAR_DADO_PARA_CONTATO;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="dado-contato" method="post" action="<?= \DL::$dir_raiz; ?>">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->dado_contato_id; ?>" />
        <?php endif; ?>

        <label for="tipo"><?= TXT_LABEL_TIPO; ?>:</label><br />
        <select name="tipo" id="tipo" title="<?= TXT_LABEL_TIPO; ?>">
            <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>
            
            <?php foreach( $params['tipos'] as $t ): ?>
            <option value="<?= $t['tipo_dado_id']; ?>"<?= $t['tipo_dado_id'] == $mod->dado_contato_tipo ? ' SELECTED' : ''; ?>>
                <?= $t['tipo_dado_descr']; ?>
            </option>
            <?php endforeach; ?>
        </select>
        <br /><br />
        
        <label for="descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br />
        <input type="text" name="descr" id="descr" value="<?= $mod->dado_contato_descr; ?>" title="<?= TXT_LABEL_DESCRICAO; ?>" />
        <br /><br />

        <label><?= TXT_LABEL_PUBLICAR; ?></label>
        <input type="checkbox" name="publicar" id="publicar" value="1" class="s-ou-n"<?= $mod->dado_contato_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
        <label for="publicar"></label>
        <br /><br />
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='dado-contato']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/web-site/dados-para-contato/lista";
            },
            <?php endif; ?>
            controle: "dadocontato/salvar",
            campos  : {
                "descr"     : { obr: true },
                "tipo"      : { obr: true, validacao: /^\d+$/ },
                "publicar"  : { obr: true, marcarobr: false, validacao: /^[0-1]$/ }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    };
    //]]>
</script>
