<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 18/06/2014 08:46:23
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->album_id);

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_ALBUM_DE_FOTOS : TXT_TITULO_FORMULARIO_ALTERAR_ALBUM_DE_FOTOS;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="album" method="post" action="<?= \DL::$dir_raiz; ?>" enctype="multipart/form-data">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->album_id; ?>" />
        <?php endif; ?>
        
        <fieldset>
            <legend><?= TXT_LEGENDA_INFORMACOES_ALBUM_DE_FOTOS; ?></legend>
            
            <label for="nome"><?= TXT_LABEL_NOME; ?>:</label><br />
            <input type="text" name="nome" id="nome" value="<?= $mod->album_nome; ?>" title="<?= TXT_LABEL_NOME; ?>" />
            <br /><br />
            
            <?php if( !$editando ): ?>
            <label for="fotos"><?= TXT_LABEL_SELECIONE_UMA_OU_MAIS_FOTOS; ?>:</label><br />
            <input type="file" name="fotos[]" id="fotos" multiple="multiple" title="<?= TXT_LABEL_SELECIONE_UMA_OU_MAIS_FOTOS; ?>" />
            <br /><br />
            <?php endif; ?>
            
            <label><?= TXT_LABEL_PUBLICAR; ?></label>
            <input type="checkbox" name="publicar" id="publicar" value="1" class="s-ou-n"<?= $mod->album_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
            <label for="publicar"></label>
        </fieldset>
        
        <button type="submit"><?= $editando ? TXT_BOTAO_SUBMIT_SALVAR : TXT_BOTAO_SUBMIT_SALVAR_E_ENVIAR_AS_FOTOS; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
    
    <?php if( $editando ): ?>
    <form name="upload_fotos" method="post" action="<?= \DL::$dir_raiz; ?>" enctype="multipart/form-data">
        <fieldset>
            <legend><?= TXT_LEGENDA_FOTOS; ?></legend>
            
            <label for="fotos"><?= TXT_LABEL_SELECIONE_UMA_OU_MAIS_FOTOS; ?>:</label><br />
            <input type="file" name="fotos[]" id="fotos" multiple="multiple" title="<?= TXT_LABEL_SELECIONE_UMA_OU_MAIS_FOTOS; ?>" />
            
            <button type="submit"><?= TXT_BOTAO_SUBMIT_ENVIAR; ?></button>
        </fieldset>
    </form>
    
    <div class="todas-fotos">
        <?php foreach( $params['fotos'] as $f ): ?>
        <figure class="editar-foto" id="foto-<?= $f['foto_album_id']; ?>">
            <img src="<?= \DL::$dir_raiz .'/'. $f['foto_album_imagem']; ?>" />
            
            <figcaption>
                <p>
                    <b><?= TXT_LABEL_TITULO; ?>:</b> <em><?= $f['foto_album_titulo']; ?></em>
                </p>
                
                <?php if( $f['foto_album_capa'] == 1 ): ?>
                <span class="capa"><?= MSG_CAPA; ?></span>                
                <?php endif; ?>
                
                <a href="javascript:;"
                   onclick="RemoverFoto(<?= $f['foto_album_id']; ?>);"
                   class="lista remover" title="<?= TXT_LINK_TITLE_REMOVER_ESSA_FOTO; ?>"
                   style="float: right; margin: 0;"><?= TXT_LINK_REMOVER; ?></a>
                   
                <a href="javascript:;" 
                   onclick="AbrirForm('<?= \DL::$dir_raiz; ?>/painel-dl/web-site/fotos/alterar/<?= $f['foto_album_id']; ?>');" 
                   class="lista editar" title="<?= TXT_LINK_TITLE_EDITAR_INFORMACOES_DESSA_FOTO; ?>"
                   style="float: right;"><?= TXT_LINK_EDITAR; ?></a>
            </figcaption>
        </figure>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='album']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/web-site/albuns-de-fotos/lista";
            },
            <?php endif; ?>
            controle: "album/salvar",
            campos  : {
                "nome"      : { obr: true },
                "publicar"  : { obr: true, marcarobr: false, validacao: /^[0-1]$/ }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        
        <?php if( $editando ): ?>
        $("form[name='upload_fotos']")._dlformulario({
            controle: "fotoalbum/upload/<?= $mod->album_id; ?>",
            depois  : function(){ window.location.reload(); },
            campos  : {
                "fotos": { obr: true }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        <?php endif; ?>
    };
    
    function RemoverFoto(id_foto){
        $.ajax({
            url     : "<?= \DL::$dir_raiz; ?>/fotoalbum/remover",
            data    : "id[]="+ id_foto,
            type    : "post",
            success : function(json){
                var resp = TratarResposta(json);
                
                $("body")._dlmostrarmsg({
                    mensagem    : resp.msg,
                    tipo        : ["alerta", resp.ret],
                    botao       : { texto: "x", funcao: function(){ $("#foto-"+ id_foto).fadeOut("fast", function(){ $(this).remove(); }); } },
                    aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" }
                });
            }
        });
    } // Fim function RemoverFoto(id_foto)
    //]]>
</script>