<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: Site buffetsalakaboom.com.br
 * @Data	: 09/01/2014
 */

?>

<div class="dl login">
	<h1><?= TXT_TITULO_ACESSO_AOS_CONVITES_VIRTUAIS; ?></h1>
	
	<?= $params['pg_texto']; ?>
	
	<form name="convite" method="post" action="<?= \DL::$dir_raiz; ?>">
            <label for="usuario"><?= TXT_LABEL_LOGIN; ?>:</label><br />
            <input type="text" name="usuario" id="usuario" title="<?= TXT_LABEL_LOGIN; ?>" required />
            <br /><br />

            <label for="senha"><?= TXT_LABEL_SENHA; ?>:</label><br />
            <input type="password" name="senha" id="senha" title="<?= TXT_LABEL_SENHA; ?>" required />
            <br /><br />

            <button type="submit"><?= TXT_BOTAO_SUBMIT_ENTRAR; ?></button>
	</form>
</div>

<script>
	//<![CDATA[
    window.onload = function(){
        $("form[name='convite']")._dlformulario({
            controle: "convitevirtual/fazerlogincv",
            depois	: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/convites-virtuais";
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "salakaboom" }
        });
    };
	//]]>
</script>