<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 29/06/2014 18:09:20
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->tipo_parceiro_id);

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_TIPO_PARCEIRO : TXT_TITULO_FORMULARIO_ALTERAR_TIPO_PARCEIRO;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="tipo-parceiro" method="post" action="<?= \DL::$dir_raiz; ?>">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->tipo_parceiro_id; ?>" />
        <?php endif; ?>
                
        <label for="descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br />
        <input type="text" name="descr" id="descr" value="<?= $mod->tipo_parceiro_descr; ?>" title="<?= TXT_LABEL_DESCRICAO; ?>" />
        <br /><br />

        <label><?= TXT_LABEL_PUBLICAR; ?></label>
        <label>
            <input type="radio" name="publicar" value="1"<?= $mod->tipo_parceiro_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
            <?= TXT_OPCAO_SIM; ?>
        </label>

        <label>
            <input type="radio" name="publicar" value="0"<?= $mod->tipo_parceiro_publicar == 0 ? ' CHECKED' : ''; ?> />
            <?= TXT_OPCAO_NAO; ?>
        </label>
        <br /><br />
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='tipo-parceiro']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/salakaboom/tipos-de-parceiros/lista";
            },
            <?php endif; ?>
            controle: "tipoparceiro/salvar",
            campos  : {
                "descr"     : { obr: true },
                "publicar"  : { obr: true, marcarobr: false, validacao: /^[0-1]{1}$/ }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    };
    //]]>
</script>