<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 29/06/2014 18:09:20
 */

$mod = $params['modelo'];

# Verificar se o registro está sendo editado
$editando = !is_null($mod->cardapio_id);

# Definir qual título deve ser inserido na TAG H1
$titulo_h1 = !$editando ? TXT_TITULO_FORMULARIO_NOVO_CARDAPIO : TXT_TITULO_FORMULARIO_ALTERAR_CARDAPIO;

?>

<div class="dl">
    <h1><?= $titulo_h1; ?></h1>
    
    <?php include_once './visoes/painel-dl/_titulo-h2.phtml'; ?>
    
    <form name="cardapio" method="post" action="<?= \DL::$dir_raiz; ?>">
        <?php if( $editando ): ?>
        <!-- ID do registro atual -->
        <input type="hidden" name="id" value="<?= $mod->cardapio_id; ?>" />
        <?php endif; ?>
        
        <fieldset>
            <legend><?= TXT_LEGENDA_INFORMACOES_DO_CARDAPIO; ?></legend>
            
            <label for="titulo"><?= TXT_LABEL_TITULO; ?>:</label><br />
            <input type="text" name="titulo" id="titulo" value="<?= $mod->cardapio_titulo; ?>" title="<?= TXT_LABEL_TITULO; ?>" />
            <br /><br />

            <label for="descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br />
            <textarea name="descr" id="descr" title="<?= TXT_LABEL_DESCRICAO; ?>"><?= $mod->cardapio_descr; ?></textarea>
            <br /><br />

            <label for="ordem"><?= TXT_LABEL_ORDEM; ?>:</label><br />
            <input type="number" name="ordem" id="ordem" value="<?= $mod->cardapio_ordem; ?>" title="<?= TXT_LABEL_ORDEM; ?>" />
            <br /><br />

            <label><?= TXT_LABEL_PUBLICAR; ?></label>
            <input type="checkbox" name="publicar" id="publicar" value="1" class="s-ou-n"<?= $mod->cardapio_publicar == 1 || !$editando ? ' CHECKED' : ''; ?> />
            <label for="publicar"></label>
        </fieldset>
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
    
    <?php if( $editando ): ?>
    <form name="item-cardapio" method="post" action="<?= \DL::$dir_raiz; ?>">
        <!-- ID do cardapio atual -->
        <input type="hidden" name="item_cardapio" value="<?= $mod->cardapio_id; ?>" />
        
        <fieldset>
            <legend><?= TXT_LEGENDA_ITENS_DO_CARDAPIO; ?></legend>
            
            <label for="descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br />
            <input type="text" name="descr" id="descr" title="<?= TXT_LABEL_DESCRICAO; ?>" />
            
            <input type="hidden" name="publicar" value="1" />
            
            <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        </fieldset>
        
        <?php if( count($params['itens']) > 0 ): ?>
        <table class="lista">
            <tr>
                <th id="id" class="td-id"></th>
                <th id="descr"><?= TXT_TABELA_TITULO_DESCRICAO; ?></th>
                <th id="opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
            </tr>
            
            <?php foreach( $params['itens'] as $i ): ?>
            <tr>
                <td headers="id" class="td-id">
                    <input type="checkbox" name="id[]" value="<?= $l['item_cardapio_id']; ?>" />
                </td>
                <td headers="descr"><?= $i['item_cardapio_descr']; ?></td>
                <td headers="opcoes" class="td-opcoes">
                    <a href="javascript:;" class="lista remover" title="<?= TXT_LINK_TITLE_REMOVER_REGISTRO; ?>" onclick="if( SelecionarLinha(this) ) RemoverItem('<?= MSG_PADRAO_DESEJA_REALMENTE_REMOVER_ESSE_REGISTRO; ?>', <?= $i['item_cardapio_id']; ?>);">
                        <?= TXT_LINK_REMOVER; ?>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </form>
    <?php endif; ?>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='cardapio']")._dlformulario({
            <?php if( !$editando ): ?>
            depois: function(){
                window.location = "<?= \DL::$dir_raiz; ?>/painel-dl/salakaboom/cardapios/lista";
            },
            <?php endif; ?>
            controle: "cardapio/salvar",
            campos  : {
                "titulo": { obr: true },
                "descr" : { obr: true },
                "ordem" : { obr: true, validacao: EXPR_APENAS_NUMEROS }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        
        <?php if( $editando ): ?>
        $("form[name='item-cardapio']")._dlformulario({
            depois: function(){
                window.location.reload();
            },
            controle: "itemcardapio/salvar/<?= $mod->cardapio_id; ?>",
            campos  : {
                "descr" : { obr: true }
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        <?php endif; ?>
    };
    
    function RemoverItem(mensagem, id){
        if( !confirm(mensagem) )
            return false;
        
        $.ajax({
            url     : "<?= \DL::$dir_raiz; ?>/itemcardapio/remover",
            type    : "post",
            data    : "id[]="+ id,
            success : function(json){
                var resp = TratarResposta(json);
                
                $("body")._dlmostrarmsg({
                    mensagem    : resp.msg,
                    tipo        : ["alerta", resp.ret],
                    botao       : { texto: "x", funcao: function(){ 
                            $(":checkbox[name='id[]']:checked").parents("tr").slideUp(500, function(){ $(this).remove(); });
                        } },
                    aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" }
                });
            }
        });
    } // Fim RemoverItem(mensagem)
    //]]>
</script>