<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: Aug 4, 2014 11:37:04 AM
 */

?>

<!-- Formulário para envio de depoimento -->
<div class="dl depoimento">
    <h1><?= TXT_TITULO_ENVIAR_UM_DEPOIMENTO; ?></h1>
    
    <form name="depoimento" action="<?= \DL::$dir_raiz; ?>" method="post">          
        <label for="nome"><?= TXT_LABEL_NOME; ?>:</label><br />
        <input type="text" name="nome" id="nome" title="<?= TXT_LABEL_NOME; ?>" />
        <br /><br />
        
        <label for="texto"><?= TXT_LABEL_DEPOIMENTO; ?>:</label><br />
        <textarea name="texto" id="texto" title="<?= TXT_LABEL_DEPOIMENTO; ?>"></textarea>
        
        <center>
            <button type="submit"><?= TXT_BOTAO_SUBMIT_ENVIAR; ?></button>
            <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
        </center>
    </form>
</div>

<script>
    //<![CDATA[
    // window.onload = function(){
        $("form[name='depoimento']")._dlformulario({
            controle    : "depoimentow/enviar",
            campos      : {
                "nome"  : { obr: true },
                "texto" : { obr: true }
            },
            depois      : function(){},
            aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    // };
    //]]>
</script>