    <!-- Java Scripts -->
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>jquery-<?= \DL::$conf_jquery_versao; ?>-min.js"></script>
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>dl-framework.js"></script>
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>dl-formulario/dl-formulario-2.0.plugin.js"></script>
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>dl-galeria/dl-galeria-2.0.plugin.js"></script>
    
    <footer class="dl">
        <?= DL::$ap_nome; ?> &COPY; <?= date('Y'); ?>
    </footer>