<?php

/**
* @Autor	: Diego Lepera
* @E-mail	: d_lepera@hotmail.com
* @Projeto	: FrameworkDL
* @Data	: 19/05/2014 18:22:01
*/

header('Content-type: text/html; charset='. \DL::$ap_encoding, true);

$params = $this->_obterparams();

?>
<!DOCTYPE html>
<html>
<head>
    <!-- Meta TAGs -->
    <meta charset="<?= \DL::$ap_encoding; ?>">
    <meta name="author" content="Diego Lepera @DL" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    
    <!-- Configurar a versão do IE suportada -->
    <meta http-equiv="X-UA-Compatible" content="IE=<?= \DL::$browser_versao_ie; ?>" />
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= \DL::$dir_raiz . \DL::$dir_imgs; ?>favicon-website.ico" />
    
    <!-- Estilos da página -->
    <link rel="stylesheet" media="all" href="<?= \DL::$dir_raiz . \DL::$dir_css; ?>todos/dl-layout.css" />
    <link rel="stylesheet" media="all" href="<?= \DL::$dir_raiz . \DL::$dir_css; ?>todos/dl-site.css" />
    <link rel="stylesheet" media="all" href="<?= \DL::$dir_raiz . \DL::$dir_css; ?>todos/lista.css" />
    <link rel="stylesheet" media="all" href="<?= \DL::$dir_raiz . \DL::$dir_js .'dl-formulario/css/'. DL::$plugin_formulario_tema; ?>/formulario.css" />

    <title><?= \DL::$ap_nome; ?></title>
</head>
<body>
        
    <header class="dl">
        <a href="<?= \DL::$dir_raiz; ?>" class="logotipo" title="<?= \DL::$ap_nome; ?>"><?= \DL::$ap_nome; ?></a>
        
        <div class="slogan">
            <?= \DL::$ap_slogan; ?>
            
            <img src="<?= \DL::$dir_raiz . \DL::$dir_imgs; ?>rosto-mago-salakaboom.png" class="rosto-salakaboom" />
        </div>
    </header>
    
    <nav class="dl">
        <h1><?= TXT_TITULO_MENU_PRINCIPAL; ?></h1>
        
        <ul>
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/o-buffet"><?= TXT_LINK_INSTITUCIONAL; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/nosso-cardapio"><?= TXT_LINK_CARDAPIO; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/albuns-de-fotos"><?= TXT_LINK_ALBUNS_DE_FOTOS; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/nossos-parceiros"><?= TXT_LINK_PARCEIROS; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/convites-virtuais"><?= TXT_LINK_CONVITES_VIRTUAIS; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/orcamento-on-line"><?= TXT_LINK_ORCAMENTO_ON_LINE; ?></a>
            </li>
            
            <li>
                <a href="<?= \DL::$dir_raiz; ?>/fale-conosco"><?= TXT_LINK_FALE_CONOSCO; ?></a>
            </li>
        </ul>
    </nav>
