<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL MVC / Site
 * @Data	: 03/04/2014
 */

$mod_i = $params['item'];

?>

<div class="dl cardapio">
    <h1><?= TXT_TITULO_CARDAPIO; ?></h1>
    
    <?= $params['txt_pagina']; ?>
    
    <ul class="cardapio">
        <?php foreach( $params['cardapios'] as $c ): ?>
	    <li>
            <h2><?= $c['cardapio_titulo']; ?></h2>
	        
	        <div class="descr"><?= $c['cardapio_descr']; ?></div>
            
            <ul class="itens">
                <?php
                # Selecionar os itens desse cardáio
                $lis_i = $mod_i->_listar("item_cardapio = {$c['cardapio_id']}", 'item_cardapio_descr', 'item_cardapio_descr');

                foreach( $lis_i as $i ): ?>
                <li><?= $i['item_cardapio_descr']; ?></li>
                <?php endforeach; ?>
            </ul>
	    </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
	//<![CDATA[
	$("ul.cardapio > li").click(function(){
        var $this = $(this);
        
        // Esconder itens que estiverem sendo mostrados
        $("ul.cardapio > li").not($this).find('.itens').slideUp("fast");
        
        // Mostrar ou esconder os itens desse cardápio
        $this.find(".itens").slideToggle("fast");
        
        window.scrollTo(0, $this.position().top);
    });
    //]]>
</script>