<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL MVC / Site
 * @Data	: 03/04/2014
 */

$mod_i = $params['item'];

?>

<div class="dl cardapio">
    <h1><?= TXT_TITULO_CARDAPIO; ?></h1>
    
    <p>Aqui você monta o cardápio da sua <strong>festa</strong> como você quiser e tudo é servido à  vontade!</p>
    
    <ul class="lista-cardapio">
        <?php foreach( $params['cardapios'] as $c ): ?>
	    <li>
            <h2><?= $c['cardapio_titulo']; ?></h2>
	        
	        <div class="cardapio-descr"><?= $c['cardapio_descr']; ?></div>
            
            <ul class="cardapio-itens">
                <?php
                # Selecionar os itens desse cardáio
                $lis_i = $mod_i->_listar("item_cardapio = {$c['cardapio_id']}", 'item_cardapio_descr', 'item_cardapio_descr');

                foreach( $lis_i as $i ): ?>
                <li><?= $i['item_cardapio_descr']; ?></li>
                <?php endforeach; ?>
            </ul>
	    </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
	//<![CDATA[
    window.onload = function(){
        $("ul.lista-cardapio > li").click(function(){
            var $this = $(this);

            // Esconder itens que estiverem sendo mostrados
            $("ul.lista-cardapio > li").not($this).find('.cardapio-itens').slideUp("fast");

            // Mostrar ou esconder os itens desse cardápio
            $this.find(".cardapio-itens").slideToggle("fast");

            window.scrollTo(0, $this.position().top);
        });
    };
    //]]>
</script>