<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: Aug 5, 2014 8:18:15 AM
 */

?>

<div class="dl certificado">
    <h1><?= TXT_TITULO_CERTIFICACAO_DE_EXCELENCIA_NO_ATENDIMENTO; ?></h1>
    
    <p>
        Os resultados dessa pesquisa, representam com exatidão as respostas atribuídas pelos pesquisadores e avaliadores por técnicos 
        devidamente capacitados. O <em>Buffet Salakaboom obteve a nota final 9,8</em> depois de serem analisados os seguintes quesitos:
    </p>
    
    <table class="lista">
        <tr>
            <th id="quesito"><?= TXT_TABELA_TITULO_QUESITO; ?></th>
            <th id="nota"><?= TXT_TABELA_TITULO_NOTA; ?></th>
        </tr>
        
        <tr>
            <td headers="quesito">Qualidade de serviços</td>
            <td headers="nota">10</td>
        </tr>
        
        <tr>
            <td headers="quesito">Qualidade de atendimento</td>
            <td headers="nota">10</td>
        </tr>
        
        <tr>
            <td headers="quesito">Recepção</td>
            <td headers="nota">9,8</td>
        </tr>
        
        <tr>
            <td headers="quesito">Higiene</td>
            <td headers="nota">10</td>
        </tr>
        
        <tr>
            <td headers="quesito">Aspecto visual</td>
            <td headers="nota">10</td>
        </tr>
        
        <tr>
            <td headers="quesito">Vestuário de funcionários</td>
            <td headers="nota">9,8</td>
        </tr>
        
        <tr>
            <td headers="quesito">Pontualidade</td>
            <td headers="nota">9,8</td>
        </tr>
        
        <tr>
            <td headers="quesito">Iluminação</td>
            <td headers="nota">9,8</td>
        </tr>
        
        <tr>
            <td headers="quesito">Atenção dos funcionários</td>
            <td headers="nota">9,8</td>
        </tr>
        
        <tr>
            <td headers="quesito">Média</td>
            <td headers="nota">9,8</td>
        </tr>
    </table>
    
    <a href="http://www.ipope.net.br/portal/index.php?option=com_content&amp;view=article&amp;id=225&amp;Itemid=75" target="_blank">
        <?= TXT_LINK_CONHECA_EMPRESAS_CERTIFICADAS_IPOPE; ?>
    </a>
</div>
