<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 20/05/2014 11:58:12
 */

?>

<div class="dl fale-conosco">
    <h1><?= TXT_TITULO_FALE_CONOSCO; ?></h1>
    
    <form name="fale-conosco" method="post" action="<?= \DL::$dir_raiz; ?>">
        <label for="nome"><?= TXT_LABEL_NOME_COMPLETO; ?>:</label><br />
        <input type="text" name="nome" id="nome" title="<?= TXT_LABEL_NOME_COMPLETO; ?>" required />
        <br /><br />
        
        <label for="email"><?= TXT_LABEL_EMAIL; ?>:</label><br />
        <input type="email" name="email" id="email" title="<?= TXT_LABEL_EMAIL; ?>" required />
        <br /><br />
        
        <label for="telefone"><?= TXT_LABEL_TELEFONE; ?>:</label><br />
        <input type="text" name="telefone" id="telefone" title="<?= TXT_LABEL_TELEFONE; ?>" />
        <br /><br />
        
        <label for="assunto"><?= TXT_LABEL_ASSUNTO; ?>:</label><br />
        <select name="assunto" id="assunto" title="<?= TXT_LABEL_ASSUNTO; ?>" required>
            <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>
            
            <?php foreach( $params['assuntos'] as $ac ): ?>
                <option value="<?= $ac['assunto_contato_id']; ?>"><?= $ac['assunto_contato_descr']; ?></option>
            <?php endforeach; ?>
        </select>
        <br /><br />
        
        <label for="mensagem"><?= TXT_LABEL_MENSAGEM; ?>:</label><br />
        <textarea name="mensagem" id="mensagem" title="<?= TXT_LABEL_MENSAGEM; ?>" required></textarea>
        <br /><br />
        
        <button type="submit"><?= TXT_BOTAO_SUBMIT_ENVIAR; ?></button>
        <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
    </form>
    
    <div class="dados-para-contato">
        <p>Para melhor atendê-lo também disponibilizamos os canais de comunicação abaixo:</p>
        
        <ul class="contato">
            <?php foreach( $params['contatos'] as $c ): ?>
            <li>
                <?= $c['tipo_dado_descr']; ?>: <?= $c['dado_contato_descr']; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        
        <p>... e não deixe de nos acompanhar nas redes sociais:</p>
        
        <ul class="redes-sociais">
            <?php foreach( $params['redes-sociais'] as $rs ): ?>
            <li>
                <a href="<?= urlencode($rs['dado_contato_descr']); ?>" target="_blank">
                    <img src="<?= \DL::$dir_raiz .'/'. $rs['tipo_dado_icone']; ?>" alt="<?= $rs['tipo_dado_descr']; ?>" />
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        $("form[name='fale-conosco']")._dlformulario({
            reset   : true,
            controle: "contatosite/enviar",
            campos  : {
                "telefone"  : { mascara: MASK_CELULAR_9 },
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
    };
    //]]>
</script>