<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 20/05/2014 11:58:12
 */

?>

<div class="dl institucional">
    <h1><?= TXT_TITULO_INSTITUCIONAL; ?></h1>
    
    <div id="inst-linha-tempo">
        <?php
            # Idade do buffet salakaboom
            $idade = date('Y') - 2006;
            
            for($i=0; $i<=$idade; $i++): ?>
            <div class="ano">
                <strong><?= $i+2006; ?></strong>
            </div>
        <?php endfor; ?>                    
    </div>
    
    <p>
        O <strong>Buffet Salakaboom</strong> foi criado com o objetivo de mudar o antigo conceito de festa infantil. Investindo em 
        brinquedos de última geração e uma equipe de trabalho muito bem treinada, a festa vira <strong>uma grande diversão para toda a 
        família</strong>!
    </p>
    
    <p>
        Inicialmente montado na Rua Cipriano Barata no Ipiranga, com 700m<sup>2</sup> já era considerado um dos maiores buffets da região. 
        Menos de 1 ano após sua inauguração, com mais de 120 festas realizadas só no segundo semestre de 2006 foi anunciada a venda do 
        terreno, obrigando o buffet mudar de endereço.
    </p>
    
    <p>
        MUDOU!! E para (BEM) melhor! Hoje, em seu novo endereço R. Agostinho Gomes, 2604, também no Ipiranga, com MAIS de 1000m<sup>2</sup>
        de <strong>área plana e pura diversão</strong>, o <strong>Buffet Salakaboom</strong> continua sendo <strong>considerado um dos 
        maiores buffets da região</strong>, mas dessa vez não apenas no tamanho, mas também no atendimento, nos brinquedos e nas 
        realizações das festas que são consideradas as  mais animadas da região!
   </p>
   
   <div id="inst-fotos"></div>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        /**
         * Definir o tamanho dos elementos da linha do tempo
         */
        var $anos = $("#inst-linha-tempo .ano");
            $anos.css({
                width: (100/$anos.length) +"%"
            });
            
        /**
         * Iniciar a galeria de imagens
         */
        $("#inst-fotos")._dlgaleria({
            fotos       : [
                <?php foreach( $params['fotos'] as $f ): ?>
                {
                    src: "<?= $f['foto_album_imagem']; ?>"
                },
                <?php endforeach; ?>
            ],
            aparencia   : { tema: "<?= \DL::$plugin_galeria_tema; ?>", estilo: "linha-tempo" }
        });
    };
    //]]>
</script>