<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: Aug 5, 2014 10:27:20 AM
 */

?>

<frameset>
    <!-- Google Maps -->
    <frame
        class="google-maps"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB8NttgcTPTQ7yZcVS-kpgZxG5CnUT180Q
          &q=Rua+Agostinho+Gomes,+2604-Ipiranga,+São+Paulo" />
</frameset>