<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: Framework MVC
 * @Data	: 14/09/2013
 */

$mod	= $params['modelo'];

?>
<div class="dl parceiros">
	<h1><?= TXT_TITULO_PARCEIROS; ?></h1>
	
	<?php foreach( $params['tipos'] as $tp ):
       	$lis_p = $mod->_listar("parceiro_tipo = {$tp['tipo_parceiro_id']}", 'parceiro_imagem, parceiro_nome, parceiro_descr, parceiro_telefone, parceiro_email, parceiro_site'); ?>
        <ul class="parceiros-lista">
            <?php if( count($lis_p) > 0 ): ?>
            <li>
                <h2><?= $tp['tipo_parceiro_descr']; ?></h2>
                
                <ul class="parceiro">
                    <?php foreach( $lis_p as $p ): ?>
                    <li class="parceiro-cartao">
                        <img src="<?= \DL::$dir_raiz ."/{$p['parceiro_imagem']}"; ?>" title="<?= $p['parceiro_nome']; ?>" alt="Logotipo de empresa parceira: <?= $p['parceiro_nome']; ?>" />
                        <p class="parceiro-descr">
                            <h3><?= $p['parceiro_nome']; ?></h3>

                            <?= TXT_LABEL_TELEFONE; ?>: <?= $p['parceiro_telefone']; ?><br />
                            <?= TXT_LABEL_EMAIL; ?>: <?= !empty($p['parceiro_email']) ? "<a href=\"mailto: {$p['parceiro_email']};\">{$p['parceiro_email']}</a>" : "-"; ?><br />
                            <?= TXT_LABEL_SITE; ?>: <?= !empty($p['parceiro_site']) ? "<a href=\"http://{$p['parceiro_site']}\" target=\"_blank\" rel=\"nofollow\">{$p['parceiro_site']}</a>" : "-"; ?><br />
                            <?= TXT_LABEL_DESCRICAO; ?>: <?= nl2br($p['parceiro_descr']); ?>
                        </p>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    <?php endif;
endforeach; ?>
</div>