<?php require_once '_topo.phtml'; ?>
    
    <form name="login" id="form-login" method="post" action="<?= \DL::$dir_raiz; ?>">
        <fieldset>
            <label for="login"><?= TXT_LABEL_LOGIN; ?>:</label>
            <input type="text" name="info_login" id="login" title="<?= TXT_LABEL_LOGIN; ?>" placeholder="<?= TXT_LABEL_LOGIN; ?>" />
            <br /><br />

            <label for="senha"><?= TXT_LABEL_SENHA; ?>:</label>
            <input type="password" name="info_senha" id="senha" title="<?= TXT_LABEL_SENHA; ?>" placeholder="<?= TXT_LABEL_SENHA; ?>" />
        </fieldset>
        
        <div class="form-botoes">
            <button type="submit"><?= TXT_BOTAO_ENTRAR; ?></button>
            
            <a href="<?= \DL::$dir_raiz; ?>/painel-dl/admin/usuarios/esqueci-minha-senha">
                <?= TXT_LINK_ESQUECI_MINHA_SENHA; ?>
            </a>
        </div>
    </form>
    
    <?php require_once '_rodape.phtml'; ?>

    <script>
        //<![CDATA[
        $("form[name='login']")._dlformulario({
            controle: "usuario/fazerlogin",
            campos  : {
                "info_login": { obr: true, marcarobr: false },
                "info_senha": { obr: true, marcarobr: false }
            },
            depois  : function(){
                window.location.reload();
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }      
        });
        //]]>
    </script>
