<?php require_once '_topo.phtml'; ?>
    
    <form name="login" id="form-login" method="post" action="<?= \DL::$dir_raiz; ?>">        
        <fieldset>
            <label for="login"><?= TXT_LABEL_ESQUECI_MINHA_SENHA; ?>:</label><br />
            <input type="text" name="login" id="login" title="<?= TXT_LABEL_LOGIN; ?>" placeholder="<?= TXT_LABEL_ESQUECI_MINHA_SENHA; ?>" />
        </fieldset>
        
        <div class="form-botoes">
            <button type="submit"><?= TXT_BOTAO_SUBMIT_ENVIAR; ?></button>
            
            <a href="javascript:;" onclick="history.back();">
                <?= TXT_LINK_VOLTAR; ?>
            </a>
        </div>
    </form>
    
    <?php require_once '_rodape.phtml'; ?>
    
    <script>
        //<![CDATA[
        $("form[name='login']")._dlformulario({
            controle: "usuario/esquecisenha",
            campos  : {
                "login": { obr: true, marcarobr: false }
            },
            depois  : function(){
                history.back();
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }      
        });
        //]]>
    </script>
