<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 28/05/2014 11:52:27
 */

$perm = $params['perm'];

?>

<div class="dl">
    <h1><?= TXT_TITULO_CONFIGURACOES_DE_EMAILS; ?></h1>
    
    <div class="mais-opcoes">
        <?php if( $perm['inserir'] ): ?>
        <a href="<?= \DL::$dir_raiz; ?>/painel-dl/admin/emails/novo" class="inserir" title="<?= TXT_LINK_TITLE_INSERIR_REGISTRO; ?>">
            <?= TXT_LINK_NOVA_CONFIGURACAO_DE_EMAIL; ?>
        </a>
        <?php endif; ?>
        
        <?php include_once './visoes/painel-dl/_form_filtro.phtml'; ?>
    </div>
    
    <form name="editar-lista" method="post" action="<?= \DL::$dir_raiz; ?>">
        <table class="lista">
            <tr>
                <th id="id" class="td-id"><input type="checkbox" /></th>
                <th id="descr"><?= TXT_TABELA_TITULO_DESCRICAO; ?></th>
                <th id="host"><?= TXT_TABELA_TITULO_HOST; ?></th>
                <th id="porta"><?= TXT_TABELA_TITULO_PORTA; ?></th>
                <th id="principal"><?= TXT_TABELA_TITULO_PRINCIPAL; ?></th>
                <th id="opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
            </tr>

            <?php 
            if( !count($params['lista']) )
                echo '<tr><td colspan="6">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
            
            foreach( $params['lista'] as $l ): ?>
            <tr>
                <td headers="id" class="td-id">
                    <input type="checkbox" name="id[]" value="<?= $l['config_email_id']; ?>" />
                </td>
                <td headers="descr"><?= $l['config_email_titulo']; ?></td>
                <td headers="host"><?= $l['config_email_host']; ?></td>
                <td headers="porta"><?= $l['config_email_porta']; ?></td>
                <td headers="principal"><?= $l['PRINCIPAL']; ?></td>
                <td headers="opcoes" class="td-opcoes">
                    <?php if( $perm['ver'] ): ?>
                    <a href="javascript:;" class="lista email" onclick="Testar(<?= $l['config_email_id']; ?>);" title="<?= TXT_LINK_TITLE_TESTAR_CONFIGURACOES_DE_EMAIL; ?>">
                        <?= TXT_LINK_TESTAR; ?>
                    </a>
                    <?php endif;
                    
                    if( $perm['editar'] ): ?>
                    <a href="<?= \DL::$dir_raiz; ?>/painel-dl/admin/emails/alterar/<?= $l['config_email_id']; ?>" class="lista editar" title="<?= TXT_LINK_TITLE_EDITAR_REGISTRO; ?>">
                        <?= TXT_LINK_EDITAR; ?>
                    </a>
                    <?php endif;
                
                    if( $perm['remover'] ): ?>
                    <a href="javascript:;" class="lista remover" title="<?= TXT_LINK_TITLE_REMOVER_REGISTRO; ?>" onclick="if( SelecionarLinha(this) ) RemoverRegistro('<?= MSG_PADRAO_DESEJA_REALMENTE_REMOVER_ESSE_REGISTRO; ?>');">
                        <?= TXT_LINK_REMOVER; ?>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            
            <tr class="com-marcados">
                <td colspan="6">
                    <?php if( $perm['remover'] ): ?>
                    <a href="javascript:;" class="remover" title="<?= TXT_LINK_TITLE_REMOVER_REGISTROS_SELECIONADOS; ?>" onclick="RemoverRegistro('<?= MSG_PADRAO_DESEJA_REALMENTE_REMOVER_REGISTROS_SELECIONADOS; ?>');">
                        <?= TXT_LINK_REMOVER; ?>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
        
        <div id="paginacao"></div>
    </form>
</div>

<script>
    //<![CDATA[
    window.onload = function(){
        <?php if( $perm['remover'] ): ?>
        $editar_lista = $("form[name='editar-lista']")._dlformulario({
            controle    : "configemail/remover",
            depois      : function(){
                $(".lista :checkbox:checked").parents("tr").remove();
            },
            cktodos     : [true, "tr:first-child :checkbox:first-child", ":checkbox[name='id[]']"],
            aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }
        });
        <?php endif; ?>
        
        $("#paginacao")._dlpaginacao({
            pgtotal     : <?= $params['qtde_pg']; ?>,
            mostrar     : 5,
            aparencia   : { tema: "<?= \FrameworkDL::$plugin_paginacao_tema; ?>", estilo: "paginacao" }
        });
    };
    
    // Função para realizar o teste da configuração de envio
    function Testar(id){
        return $.ajax({
            url     : "<?= \DL::$dir_raiz; ?>/painel-dl/admin/emails/testar/"+ id,
            dataType: "text",
            success : function(json){
                var resp = TratarResposta(json);
                
                $("body")._dlmostrarmsg({
                    mensagem    : resp.msg,
                    tipo        : ["alerta", resp.ret],
                    aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" },
                    botao       : { texto: "x" }
                });
            }
        });
    } // Fim function Testar(id)
    //]]>
</script>