<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 01/07/2014 10:08:32
 */
 ?>

    <footer class="dl">
        <?= DL::$ap_nome; ?> &COPY; <?= date('Y') .' '. \DL::$conf_versao; ?>
    </footer>

    <!-- JavaScripts -->
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>jquery-<?= \DL::$conf_jquery_versao; ?>-min.js"></script>
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>dl-framework-min.js"></script>
    <script src="<?= \DL::$dir_raiz . \DL::$dir_js; ?>dl-formulario/dl-formulario-2.0.plugin-min.js"></script>