<?php require_once '_topo.phtml'; ?>
    
    <form id="login" name="login" method="post" action="<?= \DL::$dir_raiz; ?>">
        <a href="<?= \DL::$dir_raiz; ?>" class="logotipo">
            <?= \DL::$ap_nome; ?>
        </a>
        
        <span class="slogan"><?= \DL::$ap_slogan; ?></span>
        <br /><br />
        
        <div class="campos">
            <label for="info_login" class="com-imagem login"><?= TXT_LABEL_LOGIN; ?>:</label>
            <input type="text" name="info_login" id="info_login" title="<?= TXT_LABEL_LOGIN; ?>" class="recuado" />
            <br /><br />
        
            <label for="info_senha" class="com-imagem senha"><?= TXT_LABEL_SENHA; ?>:</label>
            <input type="password" name="info_senha" id="info_senha" title="<?= TXT_LABEL_SENHA; ?>" class="recuado" />
        </div>
        
        <center>
            <button type="submit"><?= TXT_BOTAO_ENTRAR; ?></button>
            
            <a href="<?= \DL::$dir_raiz; ?>/painel-dl/admin/usuarios/esqueci-minha-senha">
                <?= TXT_LINK_ESQUECI_MINHA_SENHA; ?>
            </a>
        </center>
    </form>
    
    <?php require_once '_rodape.phtml'; ?>

    <script>
        //<![CDATA[
        $("form[name='login']")._dlformulario({
            controle: "usuario/fazerlogin",
            campos  : {
                "info_login": { obr: true, marcarobr: false },
                "info_senha": { obr: true, marcarobr: false }
            },
            depois  : function(){
                window.location.reload();
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }      
        });
        //]]>
    </script>
