<?php require_once '_topo.phtml'; ?>
    
    <form id="login" name="login" method="post" action="<?= \DL::$dir_raiz; ?>">
        <a href="<?= \DL::$dir_raiz; ?>" class="logotipo">
            <?= \DL::$ap_nome; ?>
        </a>
        
        <span class="slogan"><?= \DL::$ap_slogan; ?></span>
        <br /><br />
        
        <?php if( $_SESSION['usuario_conf_reset'] == '1' ): ?>
        <p>
            <?= MSG_RESET_SENHA; ?>
        </p>
        <?php endif; ?>
        
        <div class="campos">
            <label for="senha_atual" class="com-imagem senha"><?= TXT_LABEL_SENHA_ATUAL; ?>:</label>
            <input type="password" name="senha_atual" id="senha_atual" title="<?= TXT_LABEL_SENHA_ATUAL; ?>" class="recuado" />
            <br /><br />

            <label for="senha_nova" class="com-imagem senha-nova"><?= TXT_LABEL_SENHA_NOVA; ?>:</label>
            <input type="password" name="senha_nova" id="senha_nova" title="<?= TXT_LABEL_SENHA_NOVA; ?>" class="recuado" />
            <br /><br />

            <label for="senha_nova_conf" class="com-imagem senha-nova-conf"><?= TXT_LABEL_SENHA_NOVA_CONF; ?>:</label>
            <input type="password" name="senha_nova_conf" id="senha_nova_conf" title="<?= TXT_LABEL_SENHA_NOVA_CONF; ?>" class="recuado" />
        </div>
        
        <center>
            <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>

            <?php if( $_SESSION['usuario_conf_reset'] == '1' ): ?>
            <a href="javascript:;" onclick="Sair();"><?= TXT_LINK_SAIR_DO_SISTEMA; ?></a>
            <?php else: ?>
            <button type="reset"><?= TXT_BOTAO_RESET_CANCELAR; ?></button>
            <?php endif; ?>
        </center>
    </form>
    
    <?php require_once '_rodape.phtml'; ?>
    
    <script>
        //<![CDATA[
        $("form[name='login']")._dlformulario({
            controle: "usuario/alterarsenha",
            campos  : {
                "senha_atual"       : { obr: true, marcarobr: false },
                "senha_nova"        : { obr: true, marcarobr: false },
                "senha_nova_conf"   : { obr: true, marcarobr: false }
            },
            antes   : function(){
                // Verificar se a senha nova e a sua confirmação coincidem
                var nova = $("#senha_nova").val();
                var conf = $("#senha_nova_conf").val();
                
                if( nova != conf ){
                    $("body")._dlmostrarmsg({
                        mensagem    : "<?= ERRO_USUARIO_ALTERARSENHA_SENHAS_NAO_CONFEREM; ?>",
                        tipo        : ["alerta", "erro"],
                        botao       : { texto: "x" },
                        aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" }
                    });
                    
                    return false;
                } // Fim if( nova != conf )
                
                return true;
            },
            depois  : function(){
                history.back();
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }      
        }).bind("reset", function(){ history.back(); });
        
        <?php if( $_SESSION['usuario_conf_reset'] == '1' ): ?>
        function Sair(){
            $.ajax({
                url     : "<?= \DL::$dir_raiz; ?>/usuario/fazerlogout",
                success : function(json){
                    var resp = TratarResposta(json);

                    $("body")._dlmostrarmsg({
                        mensagem    : resp.msg,
                        tipo        : ["alerta", resp.ret],
                        aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" },
                        botao       : { texto: "x", funcao: function(){ window.location.reload(); } }
                    });
                }
            });
        } // Fim function Sair()
        <?php endif; ?>
        //]]>
    </script>
