<?php require_once '_topo.phtml'; ?>
    
    <form id="login" name="login" method="post" action="<?= \DL::$dir_raiz; ?>">
        <!-- Hash de identificação -->
        <input type="hidden" name="hash" value="<?= $params['hash']; ?>" />
        
        <a href="<?= \DL::$dir_raiz; ?>" class="logotipo">
            <?= \DL::$ap_nome; ?>
        </a>
        
        <span class="slogan"><?= \DL::$ap_slogan; ?></span>
        <br /><br />
        
        <p>
            <?php printf(MSG_RESETAR_SENHA_VIA_EMAIL, $params['usr_nome']); ?>
        </p>
        
        <div class="campos">
            <label for="senha_nova" class="com-imagem senha-nova"><?= TXT_LABEL_SENHA_NOVA; ?>:</label>
            <input type="password" name="senha_nova" id="senha_nova" title="<?= TXT_LABEL_SENHA_NOVA; ?>" class="recuado" />
            <br /><br />

            <label for="senha_nova_conf" class="com-imagem senha-nova-conf"><?= TXT_LABEL_SENHA_NOVA_CONF; ?>:</label>
            <input type="password" name="senha_nova_conf" id="senha_nova_conf" title="<?= TXT_LABEL_SENHA_NOVA_CONF; ?>" class="recuado" />
        </div>
        
        <p>
            <?php printf(MSG_ATENCAO_AO_RESETAR_SENHA, $params['usr_nome']); ?>
        </p>
        
        <center>
            <button type="submit"><?= TXT_BOTAO_SUBMIT_SALVAR; ?></button>
        </center>
    </form>
    
    <?php require_once '_rodape.phtml'; ?>
    
    <script>
        //<![CDATA[
        $("form[name='login']")._dlformulario({
            controle: "usuario/resetarsenha",
            campos  : {
                "senha_atual"       : { obr: true, marcarobr: false },
                "senha_nova"        : { obr: true, marcarobr: false },
                "senha_nova_conf"   : { obr: true, marcarobr: false }
            },
            antes   : function(){
                // Verificar se a senha nova e a sua confirmação coincidem
                var nova = $("#senha_nova").val();
                var conf = $("#senha_nova_conf").val();
                
                if( nova != conf ){
                    $("body")._dlmostrarmsg({
                        mensagem    : "<?= ERRO_USUARIO_ALTERARSENHA_SENHAS_NAO_CONFEREM; ?>",
                        tipo        : ["alerta", "erro"],
                        botao       : { texto: "x" },
                        aparencia   : { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "mensagem" }
                    });
                    
                    return false;
                } // Fim if( nova != conf )
                
                return true;
            },
            depois  : function(){
                window.location = "<?= \DL::$dir_raiz; ?>/gerenc/home";
            },
            aparencia: { tema: "<?= \DL::$plugin_formulario_tema; ?>", estilo: "formulario" }      
        }).bind("reset", function(){ history.back(); });
        //]]>
    </script>
